### ISSUE TITLE
More filters in association steps? 

### ISSUE THREAD

**Issue by superjingjing** [kircherlab/MPRAsnakeflow#70]
1. It would be nice to have strand-sensitive mode (especially with BWA, by default it aligns both strands equally)
2. Number of mismatches allowed

**Comment by visze** [comment]
1. Technical not possible! See  #71 for more information on this.
2. Technical of course possible. But we have to think about the implementation. Maybe you can tell me some use cases. Especially when having insertions and deletions.

I think this brings in general back a CIGAR string filter. We can simply sum up the matches. And sequence length minus matches can be used as missmatches. But this will be not the case for Insertions. We can count them as additional missmatches.

Also possible will be a more stringend approach that first does not allow any insertions/deletions. Then is is simply just counting bp missmatches.

Any suggestions?

**Comment by visze** [comment]
we have now bbmap implemented. This is much better in terms of MAPq and cigar string. Right now we just have an option for mapq filtering. But we can extend
