### ISSUE TITLE
better handling of SLURM-related failures (low priority)

### ISSUE THREAD

**Issue by lotard** [kircherlab/MPRAsnakeflow#73]
Currently, pipeline fail on script side (e.g. user cancellation) does not stop SLURM processed and vice versa (e.g. out-of-memory error leads to script simply hanging).

Better handling could be introduced through:
https://stackoverflow.com/questions/52500725/snakemake-hangs-when-cluster-slurm-cancelled-a-job#59253812

**Comment by visze** [comment]
this is something snakemake specific.

Another option would be using profiles. But then every user have to create a profile to map parameters.
