### ISSUE TITLE
basic assignment workflow

### ISSUE THREAD

**Issue by apblair** [kircherlab/MPRAsnakeflow#85]
Hello,
I'd like to run the MPRA snakeflow basic assignment workflow, and I'm running into this error with sra-tools for the tutorial dataset. Thanks for your help!

```bash
$ fastq-dump --gzip --split-files SRR10800986
2023-04-06T20:23:45 fastq-dump.2.8.0 err: item not found while constructing within virtual database module - the path 'SRR10800986' cannot be opened as database or table
```

**Comment by apblair** [comment]
I speculate the error was due to the HPC or database network connectivity because the command appears to be working on NHLBI BioData Catalyst.

**Comment by pyareedash** [comment]
The command works in our cluster too. You may want to try the command `prefetch` from SRA tools as shown in the tutorial before running fastq-dump.
